version: "3.9"
services:
  backend:
    container_name: "cpp-backend"
    build:
      context: "./backend"
    volumes:
      - './backend:/app'
    ports:
      - 8080:8080
    tty: true
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - './frontend:/app'
    stdin_open: true
    ports:
      - 3000:3000