all: board.cpp
# 	g++ -Wall -std=c++17 main_test.cpp bitboard.hpp bitboard.cpp computer.hpp computer.cpp axial.hpp axial.cpp board.cpp board.hpp hexagon.cpp hexagon.hpp -o board
	g++ -Wall -std=c++17 main_test.cpp computer.hpp computer.cpp game.hpp game.cpp bitboard.hpp bitboard.cpp axial.hpp axial.cpp board.cpp board.hpp -o board

clean:
	rm -f board